[package]
name = "lazarus-ap"
version = "1.0.0"
edition = "2021"
description = "Test-driven emulator of the IBM AP-101S Space Shuttle general-purpose computer"
license = "MIT"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]

[profile.release]
opt-level = "s"
lto = true
panic = "abort"
