#!/usr/bin/env python3
"""Run every resurrected NASA flight-runtime image and check it against
modern mathematics, then regenerate roms/nasa/lab.md.

The manifest (roms/nasa/lab.json) carries each driver's result address.
Those addresses came from the ASM101S listings, which no longer exist on
any machine (docs/ROADMAP.md), so they are recorded rather than derived.
Every value is checked, so a wrong address shows up as a mismatch rather
than passing silently.

Usage: python3 tools/labcheck.py [--bin path/to/lazap-call]
"""
import json, pathlib, subprocess, sys

root = pathlib.Path(__file__).resolve().parent.parent
man = json.loads((root / "roms/nasa/lab.json").read_text())
call = "target/release/lazap-call"
if "--bin" in sys.argv:
    call = sys.argv[sys.argv.index("--bin") + 1]
if not (root / call).exists():
    sys.exit(f"{call} not built — run: cargo build --release --bins")

TOL = 2e-6
rows, ok_n, bad = [], 0, []

for e in man["entries"]:
    img = root / f"roms/nasa/{e['r']}RUN.fcm"
    if not img.exists():
        bad.append(f"{e['r']}: no image at {img.name}")
        continue
    got, err = [], None
    for at in e["at"]:
        cmd = [str(root / call), str(img), "--at", at] + (["--dp"] if e.get("dp") else [])
        p = subprocess.run(cmd, capture_output=True, text=True)
        if p.returncode:
            err = (p.stdout + p.stderr).strip()[:70]
            break
        f = p.stdout.split()
        # lazap-call prints "<status> <hex> <float>"; integer-valued
        # routines (IPROD/ISUM return in R5) must be read as the raw word.
        got.append(float(int(f[1], 16)) if e.get("int") else float(f[2]))
    if err:
        bad.append(f"{e['r']}: {err}")
        rows.append((e, None, False))
        continue
    good = all(abs(g - w) < TOL * max(1.0, abs(w)) for g, w in zip(got, e["want"]))
    ok_n += good
    if not good:
        bad.append(f"{e['r']}: got {got} want {e['want']}")
    rows.append((e, got, good))

fmt = lambda v: "[" + ", ".join(f"{x:g}" for x in v) + "]" if len(v) > 1 else f"{v[0]:.7g}"
out = ["| Routine | What it does | Input | Flight answer | Modern | |",
       "|---|---|---|---|---|---|"]
for e, got, good in rows:
    out.append(f"| `{e['r']}` | {e['desc']} | {e['in']} | "
               f"{'&mdash;' if got is None else fmt(got)} | {fmt(e['want'])} | "
               f"{'OK' if good else 'FAIL'} |")

unv = man.get("unverified", {})
imgs = unv.get("images", [])
hdr = (f"# The flight mathematics, running again\n\n"
       f"Generated by `tools/labcheck.py` — do not edit by hand.\n\n"
       f"**{ok_n} of {len(man['entries'])} routines execute and agree with modern "
       f"mathematics** to within {TOL:g} relative error.\n\n")
tail = ""
if imgs:
    tail = ("\n\n## Images that exist but are not verified\n\n"
            + unv.get("_why", "") + "\n\n"
            + "\n".join(f"- `{i}`" for i in imgs)
            + f"\n\nSo: {len(imgs) + len(man['entries'])} runnable images, "
              f"{ok_n} checked against modern mathematics.\n")
(root / "roms/nasa/lab.md").write_text(hdr + "\n".join(out) + tail)

(root / "roms/nasa/lab-results.json").write_text(json.dumps(
    [{"r": e["r"], "desc": e["desc"], "in": e["in"],
      "got": got, "want": e["want"], "ok": good}
     for e, got, good in rows], indent=1) + "\n")

for b in bad:
    print("FAIL:", b)
print(f"{ok_n}/{len(man['entries'])} routines verified")
sys.exit(1 if bad else 0)
